name: Lint and Test

on: [push, pull_request]

jobs:
  lint:
    name: Lint Codebase
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install linting dependencies
        run: |
          pip install black flake8

      - name: Check formatting with Black
        run: black --check --line-length 150 .

      - name: Run flake8 on src directory
        run: flake8 src/

  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install testing dependencies
        run: |
          pip install -r requirements-dev.txt || true
          pip install pytest

      - name: Run pytest with PYTHONPATH
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: pytest -q --disable-warnings --maxfail=1

